<?php

namespace Main;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-05 at 16:30:09.
 */
class BlogTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Blog
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() 
    {
        $this->object = new Blog;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Main\Blog::run
     * @todo   Implement testRun().
     */
    public function testRun() 
    {
        
        
    }

    /**
     * @covers Main\Blog::processRqst
     * @todo   Implement testProcessRqst().
     */
    public function testProcessRqst() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main\Blog::startController
     * @todo   Implement testStartController().
     */
    public function testStartController() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main\Blog::getConfig
     * @todo   Implement testGetConfig().
     */
    public function testGetConfig() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
