<?php
namespace Main\Config;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-06 at 01:44:53.
 */
class ConfigReaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ConfigReader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConfigReader;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Main\Config\ConfigReader::readConfig
     * @todo   Implement testReadConfig().
     */
    public function testReadConfig()
    {
        $configLocal = $this->object->readConfig();
        $this->assertArrayHasKey('app', $configLocal);
        $configProd = require BASE_DIR . '/config/appConfig.php';
        $this->assertArrayHasKey('app', $configProd);
    }
}
