<?php
namespace Main\Doctrine;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-06 at 01:44:41.
 */
class EntityManagerObjectTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var EntityManagerObject
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EntityManagerObject;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Main\Doctrine\EntityManagerObject::setEm
     * @todo   Implement testSetEm().
     */
    public function testSetEm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main\Doctrine\EntityManagerObject::getEm
     * @todo   Implement testGetEm().
     */
    public function testGetEm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
