<?php
namespace Main\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-06 at 01:45:07.
 */
class AbstractControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AbstractController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AbstractController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Main\Controller\AbstractController::notFoundAction
     * @todo   Implement testNotFoundAction().
     */
    public function testNotFoundAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main\Controller\AbstractController::getView
     * @todo   Implement testGetView().
     */
    public function testGetView()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
